FROM python:3.10.9
WORKDIR /suppermarket-api
COPY requirements.txt /suppermarket-api/
RUN pip3 install -r requirements.txt
COPY . /suppermarket-api
CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8080"]